# Generated by Django 6.0.7 on 2026-07-18 07:33

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "unit_number",
                    models.PositiveIntegerField(help_text="Unit number, e.g. 1, 2, 3"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Unit title, e.g. Intro to Trees", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Topics covered in this unit", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="teacher.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["unit_number"],
                "unique_together": {("subject", "unit_number")},
            },
        ),
    ]
